Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,6 +16,8 @@ jobs:
     timeout-minutes: 10
     
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
       - name: generate github-contribution-grid-snake.svg
         uses: Platane/snk/svg-only@v2
@@ -24,6 +26,19 @@ jobs:
           outputs: |
             dist/github-contribution-grid-snake.svg
             dist/github-contribution-grid-snake-dark.svg?palette=github-dark
+
+      - name: Debug Info
+        run: |
+          ls -R dist
+
+      - name: Check for SVG generation success
+        run: |
+          if [ -f dist/github-contribution-grid-snake.svg ]; then
+            echo "SVG generated successfully"
+          else
+            echo "Error: SVG generation failed"
+            exit 1
+          fi
 
       - name: push github-contribution-grid-snake.svg to the output branch
         uses: crazy-max/ghaction-github-pages@v3.1.0
